### ISSUE TITLE
question about rubi_baseline.py

### ISSUE THREAD

**Issue by SuNicole** [erobic/ramen#1]
It reports "no module named bootstrap" and "no module named block " when I try to execute ./ramen_VQA2.sh . This happens because the code "from bootstrap.lib.options import Options" in rubi_baseline.py . Is it an folder created by yourself? Because I can't find anything about the "block" on the Internet . I sincerely look forward to the answer from you .

**Comment by erobic** [comment]
Hi,

You can install those dependencies using: https://github.com/Cadene/block.bootstrap.pytorch.
Alternately, you could also remove the following lines from `run_network.py`, as our experiments did not use RUBi (RUBi was added much later):
```
from models.rubi import RUBiNet
from criterion.rubi_criterion import RUBiCriterion

```
Thank you for opening this issue, I will either remove RUBi completely or just update README. Please let me know if you still face issues!
