### ISSUE TITLE
Why "init_embedding" was only added to  ramen and RN?

### ISSUE THREAD

**Issue by hackerchenzhuo** [erobic/ramen#3]
Is this fair for other model?

**Comment by hackerchenzhuo** [comment]
Besides, dropout was also added to  ramen

**Comment by erobic** [comment]
Thank you for pointing these out. 

Regarding init_embedding, we ran all of the original experiments using their respective repositories and this codebase was created after that. So, if the method's code base used the initialization (e.g., BAN used it), it was run with the initialization. I will try to fix the discrepancies.

Regarding dropout, the fairest thing would have been to tune it for all methods or just not use it at all. However, at the time we considered this only for RAMEN.

**Comment by hackerchenzhuo** [comment]
Thank you .
good job.
